jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-stretch-node-browsers
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt
      - run:
          name: Install allure CLI
          command: |
            uname -a
            sudo npm install -g allure-commandline --save-dev
#            sudo npm install -g allure-comandline --save-dev
      - save_cache: # cache Python dependencies using checksum of Pipfile as the cache-key
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - run:
          name: Test
          command: |
            . venv/bin/activate
            pytest -n 4 --variables variables.json --alluredir ~/PythonCourse/allure_results_json
      - run:
          name: Reporting
          command:  |
            allure generate -c ~/PythonCourse/allure_results_json -o ~/PythonCourse/allure_results
          when: always
      - store_artifacts:
          path: ~/PythonCourse/allure_results
          destination: allure_results
          when: always